// This file was autogenerated by google/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../google/closure-library/closure/goog/base.js', ['goog'], []);
goog.addDependency('../../../../spine.js', ['spine'], []);
