// This file was autogenerated by google/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../flyover.js', ['fo'], []);
goog.addDependency('../../../../google/closure-library/closure/goog/base.js', ['goog'], []);
goog.addDependency('../../../../spine-demo.js', ['main.start'], ['fo', 'spine']);
goog.addDependency('../../../../spine.js', ['spine'], []);
